2021/04/08 21:46:43 [emerg] 1#1: host not found in upstream "kutt:3000" in /etc/nginx/nginx.conf:28
2021/07/15 13:29:10 [error] 31#31: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2021/07/15 13:29:10 [error] 31#31: *1 open() "/etc/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.22.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2021/07/15 13:29:16 [warn] 31#31: *10 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /grafana/public/build/app.63a9c1d648180e457252.js HTTP/1.1", upstream: "http://172.22.0.2:3000/public/build/app.63a9c1d648180e457252.js", host: "localhost", referrer: "http://localhost/grafana/login"
2021/07/15 13:29:16 [warn] 31#31: *13 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/2/00/0000000002 while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /grafana/public/build/unicons~app.63a9c1d648180e457252.js HTTP/1.1", upstream: "http://172.22.0.2:3000/public/build/unicons~app.63a9c1d648180e457252.js", host: "localhost", referrer: "http://localhost/grafana/login"
2021/07/15 13:29:16 [warn] 31#31: *8 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/3/00/0000000003 while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /grafana/public/build/vendors~app.63a9c1d648180e457252.js HTTP/1.1", upstream: "http://172.22.0.2:3000/public/build/vendors~app.63a9c1d648180e457252.js", host: "localhost", referrer: "http://localhost/grafana/login"
2021/07/15 13:55:27 [error] 31#31: *1 open() "/etc/nginx/html/graph" failed (2: No such file or directory), client: 172.25.0.1, server: localhost, request: "GET /graph HTTP/1.1", host: "localhost"
2021/07/15 14:04:25 [emerg] 1#1: host not found in upstream "prometheus:9090" in /etc/nginx/nginx.conf:28
2021/07/15 14:04:35 [emerg] 1#1: host not found in upstream "prometheus:9090" in /etc/nginx/nginx.conf:28
2021/07/15 14:04:46 [emerg] 1#1: host not found in upstream "prometheus:9090" in /etc/nginx/nginx.conf:28
2021/07/15 14:12:18 [error] 24#24: *13 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.27.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2021/07/15 14:12:18 [error] 24#24: *13 open() "/etc/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.27.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2021/07/16 13:40:56 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:3000/", host: "localhost"
2021/07/16 13:40:56 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2021/07/16 13:41:00 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:3000/", host: "localhost"
2021/07/16 13:41:09 [error] 30#30: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:3000/", host: "localhost"
2021/07/16 13:41:09 [error] 30#30: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost", referrer: "http://localhost/"
2021/07/16 13:41:25 [warn] 30#30: *12 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /grafana/public/build/grafana.dark.287cd4997284268b2f13.css HTTP/1.1", upstream: "http://172.18.0.4:3000/grafana/public/build/grafana.dark.287cd4997284268b2f13.css", host: "localhost", referrer: "http://localhost/grafana/login"
2021/07/16 14:00:26 [warn] 30#30: *25 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.21.0.1, server: localhost, request: "GET /grafana/public/build/DashboardPage.287cd4997284268b2f13.js HTTP/1.1", upstream: "http://172.21.0.4:3000/grafana/public/build/DashboardPage.287cd4997284268b2f13.js", host: "localhost", referrer: "http://localhost/grafana/"
2021/07/16 14:11:52 [warn] 30#30: *142 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.24.0.1, server: localhost, request: "GET /grafana/public/build/app.287cd4997284268b2f13.js.map HTTP/1.1", upstream: "http://172.24.0.4:3000/grafana/public/build/app.287cd4997284268b2f13.js.map", host: "localhost"
2021/07/16 14:11:52 [warn] 30#30: *141 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/2/00/0000000002 while reading upstream, client: 172.24.0.1, server: localhost, request: "GET /grafana/public/build/vendors~app.287cd4997284268b2f13.js.map HTTP/1.1", upstream: "http://172.24.0.4:3000/grafana/public/build/vendors~app.287cd4997284268b2f13.js.map", host: "localhost"
2021/07/16 14:30:35 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:36 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:37 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:38 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:38 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:39 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:39 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:40 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:41 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:43 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:44 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:45 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:45 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:46 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:46 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:47 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:47 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:48 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:50 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.26.0.3:3000/", host: "localhost"
2021/07/16 14:30:54 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /promteheus HTTP/1.1", upstream: "http://172.26.0.3:3000/promteheus", host: "localhost"
2021/07/16 14:30:58 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /promteheus HTTP/1.1", upstream: "http://172.26.0.3:3000/promteheus", host: "localhost"
2021/07/16 14:30:59 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: localhost, request: "GET /promteheus HTTP/1.1", upstream: "http://172.26.0.3:3000/promteheus", host: "localhost"
2021/07/16 14:44:46 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:44:49 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:44:52 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:45:06 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:45:09 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:45:12 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:45:14 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:45:18 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:45:21 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:45:26 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:45:35 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:45:50 [emerg] 1#1: host not found in upstream "grafana:3000" in /etc/nginx/nginx.conf:24
2021/07/16 14:46:35 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET /grafana/api/live/ws HTTP/1.1", upstream: "http://172.30.0.2:3000/grafana/api/live/ws", host: "localhost"
2021/07/16 14:47:35 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /grafana/api/live/ws HTTP/1.1", upstream: "http://172.31.0.3:3000/grafana/api/live/ws", host: "localhost"
2021/07/16 14:50:39 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.16.1, server: localhost, request: "GET /grafana/api/live/ws HTTP/1.1", upstream: "http://192.168.16.3:3000/grafana/api/live/ws", host: "localhost"
2021/07/16 14:52:39 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: localhost, request: "GET /grafana/api/live/ws HTTP/1.1", upstream: "http://192.168.32.3:3000/grafana/api/live/ws", host: "localhost"
2021/07/16 14:55:34 [warn] 30#30: *17 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 192.168.32.1, server: localhost, request: "GET /grafana/public/lib/monaco/min/vs/editor/editor.main.js HTTP/1.1", upstream: "http://192.168.32.3:3000/grafana/public/lib/monaco/min/vs/editor/editor.main.js", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m&editview=dashboard_json"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET /grafana/api/alerts/states-for-dashboard?dashboardId=1 HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/alerts/states-for-dashboard?dashboardId=1", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "GET /grafana/api/annotations?from=1626445861124&to=1626447661125&dashboardId=1 HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/annotations?from=1626445861124&to=1626447661125&dashboardId=1", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 15:01:03 [error] 30#30: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: localhost, request: "POST /grafana/api/datasources/proxy/1/api/v1/query_range HTTP/1.1", upstream: "http://192.168.48.3:3000/grafana/api/datasources/proxy/1/api/v1/query_range", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/16 21:24:08 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.27.0.4:3000/", host: "localhost"
2021/07/16 21:24:10 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.27.0.4:3000/", host: "localhost"
2021/07/16 21:24:30 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.27.0.4:3000/", host: "localhost"
2021/07/16 21:24:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.27.0.4:3000/", host: "localhost"
2021/07/16 21:24:52 [error] 25#25: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/ HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/", host: "localhost"
2021/07/16 21:25:07 [error] 25#25: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/ HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/", host: "localhost"
2021/07/16 21:25:07 [error] 25#25: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.27.0.4:3000/favicon.ico", host: "localhost", referrer: "http://localhost/grafana/"
2021/07/16 21:25:18 [error] 25#25: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.27.0.4:3000/", host: "localhost"
2021/07/16 21:26:38 [error] 25#25: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.27.0.4:3000/", host: "localhost"
2021/07/16 21:28:14 [error] 25#25: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://172.27.0.4:3000/", host: "localhost"
2021/07/17 05:53:19 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jetty_dispatches_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jetty_dispatches_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jetty_response_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jetty_response_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jetty_requests_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jetty_requests_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_buffers%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_buffers%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/annotations?from=1626499397421&to=1626501197421&dashboardId=2 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/annotations?from=1626499397421&to=1626501197421&dashboardId=2", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_buffers_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_buffers_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jvm_gc_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jvm_gc_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jvm_gc_seconds_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jvm_gc_seconds_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_memory_heap_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_memory_heap_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_memory_non_heap_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_memory_non_heap_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_memory_pools_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_memory_pools_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_memory_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_memory_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_threads%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_threads%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_os_memory_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_os_memory_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_os_file_descriptors%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_os_file_descriptors%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:19 [error] 32#32: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_os_cpu_load%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_os_cpu_load%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:20 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jvm_os_cpu_time_seconds%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_jvm_os_cpu_time_seconds%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:20 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_os_load_average%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_jvm_os_load_average%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:20 [error] 32#32: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_requests_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_requests_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:20 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_time_seconds_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_time_seconds_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:20 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_client_errors_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_client_errors_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:20 [error] 32#32: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_server_errors_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_server_errors_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:20 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_errors_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_errors_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:20 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_timeouts_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=increase(solr_metrics_node_timeouts_total%7Bbase_url%3D~%22.*%22%7D%5B1m%5D)&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:20 [error] 32#32: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_node_cores%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_node_cores%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/17 05:53:20 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: localhost, request: "GET /grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_node_core_root_fs_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30 HTTP/1.1", upstream: "http://172.27.0.4:3000/grafana/api/datasources/proxy/1/api/v1/query_range?query=solr_metrics_node_core_root_fs_bytes%7Bbase_url%3D~%22.*%22%7D&start=1626499380&end=1626501180&step=30", host: "localhost", referrer: "http://localhost/grafana/d/3oXGYlmnz/solr-dashboard?orgId=1&refresh=1m"
2021/07/19 11:53:48 [warn] 32#32: *8 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /grafana/public/build/app.287cd4997284268b2f13.js HTTP/1.1", upstream: "http://172.22.0.5:3000/grafana/public/build/app.287cd4997284268b2f13.js", host: "localhost", referrer: "http://localhost/grafana/login"
2021/07/19 11:53:49 [warn] 32#32: *10 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/2/00/0000000002 while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /grafana/public/build/vendors~app.287cd4997284268b2f13.js HTTP/1.1", upstream: "http://172.22.0.5:3000/grafana/public/build/vendors~app.287cd4997284268b2f13.js", host: "localhost", referrer: "http://localhost/grafana/login"
2021/07/19 11:58:32 [warn] 32#32: *1 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.25.0.1, server: localhost, request: "POST /grafana/api/dashboards/db/ HTTP/1.1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s&editview=templating"
2021/07/19 12:07:52 [warn] 31#31: *11 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.27.0.1, server: localhost, request: "POST /grafana/api/dashboards/db/ HTTP/1.1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s&editview=templating"
2021/07/19 12:16:53 [warn] 31#31: *932 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000002, client: 172.27.0.1, server: localhost, request: "POST /grafana/api/dashboards/db/ HTTP/1.1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s"
2021/07/19 12:26:30 [warn] 31#31: *1069 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000003, client: 172.27.0.1, server: localhost, request: "POST /grafana/api/dashboards/db/ HTTP/1.1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s&editview=templating"
2021/07/19 12:26:34 [warn] 31#31: *1069 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000004, client: 172.27.0.1, server: localhost, request: "POST /grafana/api/dashboards/db/ HTTP/1.1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s&editview=templating"
2021/07/19 12:27:27 [warn] 31#31: *1069 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000005, client: 172.27.0.1, server: localhost, request: "POST /grafana/api/dashboards/db/ HTTP/1.1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s&editview=templating"
2021/07/19 12:27:50 [warn] 31#31: *1069 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000006, client: 172.27.0.1, server: localhost, request: "POST /grafana/api/dashboards/db/ HTTP/1.1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s&editview=templating"
2021/07/19 12:30:16 [warn] 32#32: *19 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.28.0.1, server: localhost, request: "POST /grafana/api/dashboards/db/ HTTP/1.1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s"
2021/07/19 13:11:18 [warn] 32#32: *169 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 192.168.0.1, server: localhost, request: "POST /grafana/api/dashboards/db/ HTTP/1.1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s"
2021/07/19 13:32:20 [warn] 31#31: *33 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 192.168.16.1, server: localhost, request: "POST /grafana/api/dashboards/db/ HTTP/1.1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s&editview=templating"
2021/07/19 13:33:25 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: localhost, request: "GET /grafana/api/alerts/states-for-dashboard?dashboardId=1 HTTP/1.1", upstream: "http://192.168.32.5:3000/grafana/api/alerts/states-for-dashboard?dashboardId=1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s&editview=dashboard_json"
2021/07/19 13:33:25 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.32.1, server: localhost, request: "GET /grafana/api/annotations?from=1626700700555&to=1626701600555&dashboardId=1 HTTP/1.1", upstream: "http://192.168.32.5:3000/grafana/api/annotations?from=1626700700555&to=1626701600555&dashboardId=1", host: "localhost", referrer: "http://localhost/grafana/d/yt5eXHbMz5/solr-dashboard?orgId=1&refresh=30s&editview=dashboard_json"
